### ISSUE TITLE
gj -D <symbol> not working if only binary is used to build index

### ISSUE THREAD

**Issue by pandysong** [fcamel/gj#11]
If I only use a binary to build index, it complains:

```
pandy@ubuntu:~/gj_test$ gj -D foo
Database file "ID" is not found. Have you run "gj -i"?
```

I put a sample code and steps on how to reproduce the problem on 

https://github.com/pandysong/gj_issue_test

**Comment by fcamel** [comment]
Thanks for your report. I've fixed it in https://github.com/fcamel/gj/commit/94816900d9eb4583c2021b6833e79bb4f18a3c58
